# plotly data visualization (part 1)

In [1]:

# # install plotly and kaleido
# !pip install plotly
# !pip install kaleido

In [11]:
# import libraries
import pandas as pd
import plotly.express as px
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
names =['usman', 'ali','ahmed','umer']
heights =[5,8,6,7]
# create a dataframe
# create a line plot
fig = px.line(x=names,y=heights,title='Heights of students')
fig.show()
#  save the plot as png file
fig.write_image('./03_outputs/line_plot.png')
# save as standalone html file
fig.write_html('./03_outputs/line_plot.html')

In [4]:
# creare a bar plot
px.bar(x=names,y=heights,title='Heights of students')

# plots on titanic dataset

In [5]:
# import titanic dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
# scatter plot between two numeric variables
fig = px.scatter(df, x='age',y= 'fare' , color = 'sex' ,title='age vs fare')
fig.show()

In [7]:
df.dropna(inplace=True)
fig = px.scatter(df, x='age', y= 'fare' , color = 'sex', size='fare' ,title='plot of titanic dataset')
fig.show()
# save the plot
fig.write_image('D:/pandas_tips_tricks/02_notebooks/03_outputs.png',scale=3)

In [8]:
import plotly.graph_objects as go
# create a simple line chart
fig = go.Figure(data =go.Scatter(x=[1,2,3,4],y=[10,11,12,13]))
fig.show()

In [9]:
# customize the plot
fig.update_layout(
    title="Line plot of dummy data",
    xaxis_title="numbers",
    yaxis_title="values",
    showlegend=True
)
fig.show()
fig.show()

In [10]:
# heatmap on correlation of titanic dataset of age and fare
fig= px.imshow(df[['age','fare']].corr(),text_auto=True)
fig.show()

# 15 plots in plotly

In [41]:
df =sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
# 01 scatter plot
fig1 =px.scatter(df, x='sepal_length',y='sepal_width',color ='species')
fig1.show()
# save the plot
fig1.write_image('./03_outputs/iris_scatter.png',scale=3)

# 2 line plot

In [43]:
# sort the dataset
df =df.sort_values('sepal_length')
fig2 =px.line(df, x='sepal_length',y='sepal_width',color ='species')
fig2.show()

# 03 bar plot

In [ ]:
# group by species and get mean based on species
# df =df.groupby('species').mean().reset_index()
# df.head()

      species  sepal_length  sepal_width  petal_length  petal_width
0      setosa         5.006        3.428         1.462        0.246
1  versicolor         5.936        2.770         4.260        1.326
2   virginica         6.588        2.974         5.552        2.026

In [44]:
fig3 =px.bar(df,x='species',y='sepal_width')
fig3.show()

In [45]:
# volin plot
fig4 =px.violin(df,x='species',y='sepal_width',color='species',box=True)
fig4.show()

In [47]:
# histogram# histogram
fig5 = px.histogram(df, x='sepal_length', color='species')
fig5.show()

In [48]:
# scatter plot in 3d
fig6 = px.scatter_3d(df, x='sepal_length',y='sepal_width',z='petal_length',color='species',size='petal_width')
fig6.show()